### PR TITLE
MC cross section for Summer16 with / without extension

### PR DESCRIPTION
**Pull request by fdzyffff**

### CODE REVIEW

**Comment by georgia14** [comment]
Hi @fdzyffff 
Why did you make 2 files ? I think its only the second needed . What is the first about ?
Thanks
Georgia

**Comment by fdzyffff** [comment]
First is the same as Spring15, But now we don't have extension samples, I think this file should be used to calculate rate for current situation

**Comment by georgia14** [comment]
Can you also explain one example how did you compute the weights for one process ?
Thanks, Georgia

**Comment by fdzyffff** [comment]
I will remove the first file, it is a backup.
for weight, 
Xsection(Pt_30to50) = 1.41E+08 
N(Pt_30to50) = 9,978,150 
N(Pt_30to50_ext) =  29,744,744  
weight(Pt_30to50) = 9978150 / (9978150 + 29744744) = 0.2512
Xsection(Pt_30to50_weighted) = 1.41E+08 * 0.2512
Xsection(Pt_30to50_ext_weighted) = 1.41E+08 * 0.7488

**Comment by georgia14** [comment]
great

**Pull request merged**
